### ISSUE TITLE
Add to Bag(day-4)

### ISSUE THREAD

**Issue by starboy1010** [ShaktiSingh2605/brawny-jam-9247#8]
1. When adding items to the bag, the item count on the icon of the bag should update correctly. 
2." Add to bag" button changes to "Go to bag" if item is already in bag and  it should show an alert saying "Already in bag".

**Task:-**

- [x] Create an  **Add to back** page.
- [x] Item should append properly in bag.
- [x] Count of item should be visible on top.
- [x] Create **Remove** and **Add to Wishlist** button.
- [x] Quantity** change selector.
- [x] Total bill should be visible.
- [x] Create **Checkout** or **Add Address** button.
